"""empty message

Revision ID: 2e23dc7f04a1
Revises: 0a0c4ac21df6
Create Date: 2021-02-12 15:19:14.376924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e23dc7f04a1'
down_revision = '0a0c4ac21df6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=200), nullable=False))
    op.add_column('user', sa.Column('nickname', sa.String(length=100), nullable=True))
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('phone', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
